hmcts/sds-toffee-shared-infrastructure

servicebus.tf
state.tf
variables.tf

upgrading terraform and azurerm
will delete the service bus after an apply just to make sure its all ok for the sds side
```
[ ] Yes
[x] No
```

DTSPO-6371 - upgrade azurerm 

---

servicebus.tf

This creates a basic service bus for the recipe receiver app. I went with basic because it's all we really need for now.
```
[ ] Yes
[x] No
```

DTSPO-8169 - create basic service bus for recipe receiver app

---

servicebus.tf

Set correct id
```
[ ] Yes
[x] No
```

DTSPO-8169 - fix errors

---

sbox.tfvars
servicebus.tf

Add a default recipes queue to the toffee service bus
```
[ ] Yes
[x] No
```

DTSPO-8169 - add recipes queue and run tf format

---

servicebus.tf

Adding data owner role to plat ops team to make loading and reading from toffee queues easier
```
[ ] Yes
[x] No
```

DTSPO-8169 - add owner role to platops group

---

Jenkinsfile_CNP

Turning on branch syncing for demo and ithc
```
[ ] Yes
[x] No
```

Sync demo and ithc with master

---

servicebus.tf

This only worked before because the mi existed
```
[ ] Yes
[x] No
```

DTSPO-8169 - get mi id from module

---

Jenkinsfile_pipeline_test

https://tools.hmcts.net/jira/browse/DTSPO-11969
Was missing this in pipeline test
```
[ ] Yes
[x] No
```

DTSPO-11969 - Add expiresAfter in sbox pipeline test

---

renovate.json

Enable auto-merge for renovate PRs
```
[ ] Yes
[x] No
```

DTSPO-11734 - renovate - enable automerge

---

README.md

Reverts hmcts/sds-toffee-shared-infrastructure#72

Revert "Dummy"

---

README.md

Reverts hmcts/sds-toffee-shared-infrastructure#78

Revert "Revert "Dummy""

---

README.md

Reverts hmcts/sds-toffee-shared-infrastructure#79

Revert "Revert "Revert "Dummy"""

---

README.md

Reverts hmcts/sds-toffee-shared-infrastructure#80

Revert "Revert "Revert "Revert "Dummy""""

---

README.md

Reverts hmcts/sds-toffee-shared-infrastructure#81

Revert "Revert "Revert "Revert "Revert "Dummy"""""

---

README.md

Reverts hmcts/sds-toffee-shared-infrastructure#82

Revert "Revert "Revert "Revert "Revert "Revert "Dummy""""""

---

README.md

Removing dummy change

---

application-insights.tf

DTSPO-14929
Moving App Insights to module
Upgrading App Insights from Classic to workspace-based using [app-insights-migration-tool](https://github.com/hmcts/app-insights-migration-tool)

DTSPO-14929 - Migrating App Insights from Classic to Workspace-based.

---

import.tf

DTSPO-14929
Importing tf resources

DTSPO-14929 - adding imports

---

import.tf

DTSPO-14929
Adjusting import file

updating import file

---

import.tf

DTSPO-14929
Removing temp import file now that pipeline is green.

DTSPO-14929 - removing temp import file

---

application-insights.tf

https://tools.hmcts.net/jira/browse/DTSPO-14238
Add alerts and action groups

DTSPO-14238 - Add alerts

---

application-insights.tf
variables.tf

Jira link (if applicable)
[DTSPO-14997](https://tools.hmcts.net/jira/browse/DTSPO-14997)
Change description
Testing additional action group function in module

DTSPO-14997 Adding addition action group to module

---

application-insights.tf
variables.tf

Jira link (if applicable)
[DTSPO-14997](https://tools.hmcts.net/jira/browse/DTSPO-14997)
Change description
Testing map function in action group

DTSPO-14997 testing map function for action group

---

application-insights.tf

[DTSPO-14997](https://tools.hmcts.net/jira/browse/DTSPO-14997)

DTSPO-14997 testing email receiver in module

---

application-insights.tf

https://tools.hmcts.net/jira/browse/DTSPO-16829
Testing toffee with single action group.

DTSPO-16829 testing single action group with toffee

---

application-insights.tf

https://tools.hmcts.net/jira/browse/DTSPO-16856
Switch back to main branch after merging App insight brnach.

DTSPO-16856 - switch branch back to main branch
